### ISSUE TITLE
[Crash] Crash with Redstone Flux (using old API)

### ISSUE THREAD

**Issue by AlexanderLaptev** [bluemonster122/SimpleThings#1]
MC Version: 1.12.2
Forge version: 14.23.5.2838
Mod version: 1.6B (simplerandomstuff-1.12-2.0.0.1-beta)

Crash occurs during the pre-init state.
[Attached crash log (txt)](https://github.com/LukeGi/SimplyRandom/files/3301524/crash-2019-06-18_15.03.04-client.txt)
It seems like the crash is caused because of repacking RF api.

**Comment by Iuhegi** [comment]
the 1.12.2 version of the mod only adds metals; i never finished the port. so unless you just want copper, lead and tin i'm not sure i'll be fixing this.

**Comment by Iuhegi** [comment]
I'll change curseforge... it's misleading

**Comment by AlexanderLaptev** [comment]
Oh, ok.

**Comment by Iuhegi** [comment]
Once i finish the 1.14 port, i may consider getting it working for 1.12
