### ISSUE TITLE
Crash report for 1.14.4

### ISSUE THREAD

**Issue by Knito58** [bluemonster122/SimpleThings#3]
The mod version 0.0.5-beta clearly states it is not for 1.14.4. But I ignored this and loaded it and all was fine until I could afford 3 treefarms.
I'll put them threefarms back into storage and wait until the mod comes to 1.14.4.

MC 1.14.4, Forge 28.0.13, SimplyRandom 0.0.5-beta
https://pastebin.com/cB3br1k3

**Comment by Iuhegi** [comment]
Yeah, don't use a mod for a version of minecraft it wasn't made for...
